apiVersion: templates.servicecatalog.k8s.io/experimental
kind: ClusterInstanceTemplate
metadata:
  name: default-mysqldb
  namespace: default
  labels:
    serviceType: mysqldb # TODO: apply this automatically when the template is created
spec:
  serviceType: mysqldb
  parameters:
    location: eastus
