apiVersion: templates.servicecatalog.k8s.io/experimental
kind: InstanceTemplate
metadata:
  name: cheap-mysqldb
  namespace: default
  labels:
    serviceType: mysqldb # TODO: apply this automatically when the template is created
spec:
  serviceType: mysqldb
  classExternalName: azure-mysqldb
  planExternalName: basic50
  parameters:
    location: eastus
    resourceGroup: default
    sslEnforcement: disabled
    firewallStartIPAddress: "0.0.0.0"
    firewallEndIPAddress: "255.255.255.255"
