apiVersion: templates.servicecatalog.k8s.io/experimental
kind: InstanceTemplate
metadata:
  name: cheap-mysqldb
  namespace: default
  labels:
    serviceType: mysqldb # TODO: apply this automatically when the template is created
spec:
  serviceType: mysqldb
  parameters:
    resourceGroup: carolynvs-east
