required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "~0.1.7"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  #
  # Don't remove packages used for code generation
  #

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/apimachinery"
    unused-packages=false
