clusterServiceClassExternalName: azure-mysqldb
clusterServicePlanExternalName: basic50
parameters:
  location: centralus
  resourceGroup: default
  sslEnforcement: disabled
  firewallStartIPAddress: "0.0.0.0"
  firewallEndIPAddress: "255.255.255.255"
