// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

// This file was automatically generated by informer-gen

package experimental

import (
	time "time"

	templates_experimental "github.com/Azure/service-catalog-templates/pkg/apis/templates/experimental"
	versioned "github.com/Azure/service-catalog-templates/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
	experimental "github.com/Azure/service-catalog-templates/pkg/client/listers/templates/experimental"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BrokerInstanceTemplateInformer provides access to a shared informer and lister for
// BrokerInstanceTemplates.
type BrokerInstanceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() experimental.BrokerInstanceTemplateLister
}

type brokerInstanceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBrokerInstanceTemplateInformer constructs a new informer for BrokerInstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBrokerInstanceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBrokerInstanceTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBrokerInstanceTemplateInformer constructs a new informer for BrokerInstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBrokerInstanceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().BrokerInstanceTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().BrokerInstanceTemplates().Watch(options)
			},
		},
		&templates_experimental.BrokerInstanceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *brokerInstanceTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBrokerInstanceTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *brokerInstanceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&templates_experimental.BrokerInstanceTemplate{}, f.defaultInformer)
}

func (f *brokerInstanceTemplateInformer) Lister() experimental.BrokerInstanceTemplateLister {
	return experimental.NewBrokerInstanceTemplateLister(f.Informer().GetIndexer())
}
