// This file was automatically generated by informer-gen

package experimental

import (
	time "time"

	templates_experimental "github.com/Azure/service-catalog-templates/pkg/apis/templates/experimental"
	versioned "github.com/Azure/service-catalog-templates/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
	experimental "github.com/Azure/service-catalog-templates/pkg/client/listers/templates/experimental"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CatalogBindingInformer provides access to a shared informer and lister for
// CatalogBindings.
type CatalogBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() experimental.CatalogBindingLister
}

type catalogBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCatalogBindingInformer constructs a new informer for CatalogBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCatalogBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCatalogBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCatalogBindingInformer constructs a new informer for CatalogBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCatalogBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().CatalogBindings(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().CatalogBindings(namespace).Watch(options)
			},
		},
		&templates_experimental.CatalogBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *catalogBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCatalogBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *catalogBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&templates_experimental.CatalogBinding{}, f.defaultInformer)
}

func (f *catalogBindingInformer) Lister() experimental.CatalogBindingLister {
	return experimental.NewCatalogBindingLister(f.Informer().GetIndexer())
}
