// This file was automatically generated by informer-gen

package experimental

import (
	time "time"

	templates_experimental "github.com/Azure/service-catalog-templates/pkg/apis/templates/experimental"
	versioned "github.com/Azure/service-catalog-templates/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
	experimental "github.com/Azure/service-catalog-templates/pkg/client/listers/templates/experimental"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterInstanceTemplateInformer provides access to a shared informer and lister for
// ClusterInstanceTemplates.
type ClusterInstanceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() experimental.ClusterInstanceTemplateLister
}

type clusterInstanceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterInstanceTemplateInformer constructs a new informer for ClusterInstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterInstanceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterInstanceTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterInstanceTemplateInformer constructs a new informer for ClusterInstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterInstanceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().ClusterInstanceTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().ClusterInstanceTemplates().Watch(options)
			},
		},
		&templates_experimental.ClusterInstanceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterInstanceTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterInstanceTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterInstanceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&templates_experimental.ClusterInstanceTemplate{}, f.defaultInformer)
}

func (f *clusterInstanceTemplateInformer) Lister() experimental.ClusterInstanceTemplateLister {
	return experimental.NewClusterInstanceTemplateLister(f.Informer().GetIndexer())
}
