// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

// This file was automatically generated by informer-gen

package experimental

import (
	time "time"

	templates_experimental "github.com/Azure/service-catalog-templates/pkg/apis/templates/experimental"
	versioned "github.com/Azure/service-catalog-templates/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
	experimental "github.com/Azure/service-catalog-templates/pkg/client/listers/templates/experimental"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBindingTemplateInformer provides access to a shared informer and lister for
// ClusterBindingTemplates.
type ClusterBindingTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() experimental.ClusterBindingTemplateLister
}

type clusterBindingTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterBindingTemplateInformer constructs a new informer for ClusterBindingTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBindingTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterBindingTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterBindingTemplateInformer constructs a new informer for ClusterBindingTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBindingTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().ClusterBindingTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().ClusterBindingTemplates().Watch(options)
			},
		},
		&templates_experimental.ClusterBindingTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterBindingTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterBindingTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterBindingTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&templates_experimental.ClusterBindingTemplate{}, f.defaultInformer)
}

func (f *clusterBindingTemplateInformer) Lister() experimental.ClusterBindingTemplateLister {
	return experimental.NewClusterBindingTemplateLister(f.Informer().GetIndexer())
}
