// This file was automatically generated by informer-gen

package experimental

import (
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BindingTemplates returns a BindingTemplateInformer.
	BindingTemplates() BindingTemplateInformer
	// InstanceTemplates returns a InstanceTemplateInformer.
	InstanceTemplates() InstanceTemplateInformer
	// TemplatedBindings returns a TemplatedBindingInformer.
	TemplatedBindings() TemplatedBindingInformer
	// TemplatedInstances returns a TemplatedInstanceInformer.
	TemplatedInstances() TemplatedInstanceInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BindingTemplates returns a BindingTemplateInformer.
func (v *version) BindingTemplates() BindingTemplateInformer {
	return &bindingTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// InstanceTemplates returns a InstanceTemplateInformer.
func (v *version) InstanceTemplates() InstanceTemplateInformer {
	return &instanceTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TemplatedBindings returns a TemplatedBindingInformer.
func (v *version) TemplatedBindings() TemplatedBindingInformer {
	return &templatedBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TemplatedInstances returns a TemplatedInstanceInformer.
func (v *version) TemplatedInstances() TemplatedInstanceInformer {
	return &templatedInstanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
