// This file was automatically generated by informer-gen

package experimental

import (
	time "time"

	templatescontroller_experimental "github.com/Azure/service-catalog-templates/pkg/apis/templatescontroller/experimental"
	versioned "github.com/Azure/service-catalog-templates/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/service-catalog-templates/pkg/client/informers/externalversions/internalinterfaces"
	experimental "github.com/Azure/service-catalog-templates/pkg/client/listers/templatescontroller/experimental"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InstanceTemplateInformer provides access to a shared informer and lister for
// InstanceTemplates.
type InstanceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() experimental.InstanceTemplateLister
}

type instanceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInstanceTemplateInformer constructs a new informer for InstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInstanceTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInstanceTemplateInformer constructs a new informer for InstanceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInstanceTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().InstanceTemplates(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TemplatesExperimental().InstanceTemplates(namespace).Watch(options)
			},
		},
		&templatescontroller_experimental.InstanceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *instanceTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInstanceTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *instanceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&templatescontroller_experimental.InstanceTemplate{}, f.defaultInformer)
}

func (f *instanceTemplateInformer) Lister() experimental.InstanceTemplateLister {
	return experimental.NewInstanceTemplateLister(f.Informer().GetIndexer())
}
