apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokerinstancetemplates.templates.servicecatalog.k8s.io
spec:
  group: templates.servicecatalog.k8s.io
  version: experimental
  scope: Cluster
  names:
    plural: brokerinstancetemplates
    singular: brokerinstancetemplate
    kind: BrokerInstanceTemplate
    shortNames:
    - binstt
  validation:
    # See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
    openAPIV3Schema:
      properties:
        spec:
          required:
          - brokerName
          - serviceType
          properties:
            brokerName:
              type: string
            serviceType:
              type: string
            clusterServiceClassExternalName:
              type: string
            clusterServiceClassName:
             type: string
            clusterServicePlanExternalName:
              type: string
            clusterServicePlanName:
              type: string
            parameters:
              type: object
            parametersFrom:
              type: object
