apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app: {{ template "service-catalog-templates.name" . }}
    chart: {{ template "service-catalog-templates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app: {{ template "service-catalog-templates.name" . }}
    chart: {{ template "service-catalog-templates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - templates.servicecatalog.k8s.io
  resources:
  - instancetemplates
  - clusterinstancetemplates
  - brokerinstancetemplates
  - bindingtemplates
  - clusterbindingtemplates
  - brokerbindingtemplates
  - templatedinstances
  - templatedbindings
  verbs:
  - "*"
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  - servicebindings
  - clusterserviceclasses
  - clusterserviceplans
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app: {{ template "service-catalog-templates.name" . }}
    chart: {{ template "service-catalog-templates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccountName }}
