// This file was automatically generated by lister-gen

package experimental

// InstanceTemplateListerExpansion allows custom methods to be added to
// InstanceTemplateLister.
type InstanceTemplateListerExpansion interface{}

// InstanceTemplateNamespaceListerExpansion allows custom methods to be added to
// InstanceTemplateNamespaceLister.
type InstanceTemplateNamespaceListerExpansion interface{}
