apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bindingtemplates.templates.servicecatalog.k8s.io
spec:
  group: templates.servicecatalog.k8s.io
  version: experimental
  scope: Namespaced
  names:
    plural: bindingtemplates
    singular: bindingtemplate
    kind: BindingTemplate
    shortNames:
    - bndt
  validation:
    # See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
    openAPIV3Schema:
      properties:
        spec:
          properties:
            parameters:
              type: object
            parametersFrom:
              type: object
            secretKeys:
              type: object
