apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templatedbindings.templates.servicecatalog.k8s.io
spec:
  group: templates.servicecatalog.k8s.io
  version: experimental
  scope: Namespaced
  names:
    plural: templatedbindings
    singular: templatedbinding
    kind: TemplatedBinding
    shortNames:
    - tbnd
  validation:
    # See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject
    openAPIV3Schema:
      properties:
        spec:
          required:
          - instanceRef
          properties:
            instanceRef:
              properties:
                name:
                  type: string
              required:
              - name
            secretName:
              type: string
            parameters:
              type: object
            parametersFrom:
              type: object
            secretKeys:
              type: object
