// This file was automatically generated by lister-gen

package experimental

import (
	experimental "github.com/Azure/service-catalog-templates/pkg/apis/templates/experimental"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BrokerBindingTemplateLister helps list BrokerBindingTemplates.
type BrokerBindingTemplateLister interface {
	// List lists all BrokerBindingTemplates in the indexer.
	List(selector labels.Selector) (ret []*experimental.BrokerBindingTemplate, err error)
	// Get retrieves the BrokerBindingTemplate from the index for a given name.
	Get(name string) (*experimental.BrokerBindingTemplate, error)
	BrokerBindingTemplateListerExpansion
}

// brokerBindingTemplateLister implements the BrokerBindingTemplateLister interface.
type brokerBindingTemplateLister struct {
	indexer cache.Indexer
}

// NewBrokerBindingTemplateLister returns a new BrokerBindingTemplateLister.
func NewBrokerBindingTemplateLister(indexer cache.Indexer) BrokerBindingTemplateLister {
	return &brokerBindingTemplateLister{indexer: indexer}
}

// List lists all BrokerBindingTemplates in the indexer.
func (s *brokerBindingTemplateLister) List(selector labels.Selector) (ret []*experimental.BrokerBindingTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*experimental.BrokerBindingTemplate))
	})
	return ret, err
}

// Get retrieves the BrokerBindingTemplate from the index for a given name.
func (s *brokerBindingTemplateLister) Get(name string) (*experimental.BrokerBindingTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(experimental.Resource("brokerbindingtemplate"), name)
	}
	return obj.(*experimental.BrokerBindingTemplate), nil
}
