// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

// This file was automatically generated by lister-gen

package experimental

// BindingTemplateListerExpansion allows custom methods to be added to
// BindingTemplateLister.
type BindingTemplateListerExpansion interface{}

// BindingTemplateNamespaceListerExpansion allows custom methods to be added to
// BindingTemplateNamespaceLister.
type BindingTemplateNamespaceListerExpansion interface{}

// BrokerBindingTemplateListerExpansion allows custom methods to be added to
// BrokerBindingTemplateLister.
type BrokerBindingTemplateListerExpansion interface{}

// BrokerInstanceTemplateListerExpansion allows custom methods to be added to
// BrokerInstanceTemplateLister.
type BrokerInstanceTemplateListerExpansion interface{}

// ClusterBindingTemplateListerExpansion allows custom methods to be added to
// ClusterBindingTemplateLister.
type ClusterBindingTemplateListerExpansion interface{}

// ClusterInstanceTemplateListerExpansion allows custom methods to be added to
// ClusterInstanceTemplateLister.
type ClusterInstanceTemplateListerExpansion interface{}

// InstanceTemplateListerExpansion allows custom methods to be added to
// InstanceTemplateLister.
type InstanceTemplateListerExpansion interface{}

// InstanceTemplateNamespaceListerExpansion allows custom methods to be added to
// InstanceTemplateNamespaceLister.
type InstanceTemplateNamespaceListerExpansion interface{}

// TemplatedBindingListerExpansion allows custom methods to be added to
// TemplatedBindingLister.
type TemplatedBindingListerExpansion interface{}

// TemplatedBindingNamespaceListerExpansion allows custom methods to be added to
// TemplatedBindingNamespaceLister.
type TemplatedBindingNamespaceListerExpansion interface{}

// TemplatedInstanceListerExpansion allows custom methods to be added to
// TemplatedInstanceLister.
type TemplatedInstanceListerExpansion interface{}

// TemplatedInstanceNamespaceListerExpansion allows custom methods to be added to
// TemplatedInstanceNamespaceLister.
type TemplatedInstanceNamespaceListerExpansion interface{}
