// This file was automatically generated by lister-gen

package experimental

// BindingTemplateListerExpansion allows custom methods to be added to
// BindingTemplateLister.
type BindingTemplateListerExpansion interface{}

// BindingTemplateNamespaceListerExpansion allows custom methods to be added to
// BindingTemplateNamespaceLister.
type BindingTemplateNamespaceListerExpansion interface{}

// CatalogBindingListerExpansion allows custom methods to be added to
// CatalogBindingLister.
type CatalogBindingListerExpansion interface{}

// CatalogBindingNamespaceListerExpansion allows custom methods to be added to
// CatalogBindingNamespaceLister.
type CatalogBindingNamespaceListerExpansion interface{}

// CatalogInstanceListerExpansion allows custom methods to be added to
// CatalogInstanceLister.
type CatalogInstanceListerExpansion interface{}

// CatalogInstanceNamespaceListerExpansion allows custom methods to be added to
// CatalogInstanceNamespaceLister.
type CatalogInstanceNamespaceListerExpansion interface{}

// InstanceTemplateListerExpansion allows custom methods to be added to
// InstanceTemplateLister.
type InstanceTemplateListerExpansion interface{}

// InstanceTemplateNamespaceListerExpansion allows custom methods to be added to
// InstanceTemplateNamespaceLister.
type InstanceTemplateNamespaceListerExpansion interface{}
